### ISSUE TITLE
How do you stop (Force Finish) the current playing audio without disconnecting?

### ISSUE THREAD

**Issue by AKASGaming** [DevAndromeda/dartjs#1]
I was recently update some of my code in my bot from v12 to v13 and when I stumbled across this package, I was so excited! _**(Thank you guys sooo much for your hard work!)**_

The problem I'm currently having though is finding how to end my currently playing audio without disconnecting from the voice channel. Similar to `dispatcher.end()`. Any suggestions?

**Comment by twlite** [comment]
`dispatcher.end()` added in v1.1.0
