### ISSUE TITLE
bug: finish event emits immediately

### ISSUE THREAD

**Issue by EhsanFox** [DevAndromeda/dartjs#4]
I have tried to use it on a bot that is based on Discord.js version 13, but for some reason, the dispatcher emits the "finish" event immediately.

i'm listening for "start", "finish", "error" and "debug" events, 
I have the logs of "debug" events here:
```
from {"status":"buffering","resource":true,"stepTimeout":false}
to {"status":"playing","missedFrames":0,"playbackDuration":0,"resource":true,"stepTimeout":false}
```

No outputs from "error" events though.

The stream is also coming directly from `ytdl-core` (as it is in the example),
Here is my `PlayOptions object`:
```ts
{
     metadata: {
           ctx,
           track,
           connection
     },
     behaviours: {
           noSubscriber: NoSubscriberBehavior.Stop
     },
          inlineVolume: true,
          initialVolume: 100 / 100
}
```

any idea or any solution?

**Comment by EhsanFox** [comment]
Source code of the full command and others can be found in [here](https://github.com/SeTar-Bot/bot/blob/dev/src/bot/Components/Commands/play.ts)

**Comment by twlite** [comment]
This could be caused by ytdl stream closing immediately. Have you tried using other streams?
You could perhaps try playing local file stream and see if that works.

**Comment by EhsanFox** [comment]
I'm gonna try to run some other streams such as `IncomingMessage` type from `soundcloud-scrapper` or some `Buffers`

**Comment by EhsanFox** [comment]
Still the same result, I tried using [soundcloud-scrapper](https://www.npmjs.com/package/soundcloud-scraper) (which is already built-in the source code mine) but still the same result, it fires the finish event immediately.

**Comment by EhsanFox** [comment]
the funny thing is, the new state that is being changed, is "playing" and not even "idle" but still fires up "finish" events.

**Comment by twlite** [comment]
Just tried playing `ytdl` stream on a test bot and everything seems to be fine.

**Comment by twlite** [comment]
The procedure is simple:

```ts
const song = ytdl(vid.url, {
    highWaterMark: 1 << 25,
    filter: "audioonly",
    quality: "highestaudio"
});

connection.play(song, {
    metadata: {
        video: vid,
        message: message as Message<true>
    }
});
```

**Comment by EhsanFox** [comment]
I was using `discord-ytdl-core`, i switched to `ytdl-core` seems to be fine now.

**Comment by twlite** [comment]
> I was using `discord-ytdl-core`, i switched to `ytdl-core` seems to be fine now.

The problem could be the output format of discord-ytdl-core with input format set on voice being different.
